server:
  port: 8008
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guli?characterEncoding=utf-8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123.com
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: service-statistics
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.0.11
    port: 6379
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    #配置mp的日志输出
  mapper-locations: classpath:com/lzg/guli/statistics/mapper/xml/*.xml
feign:
  hystrix:
    enabled: true

