server:
  port: 8007

spring:
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 192.168.0.11
    port: 6379
    lettuce:
      pool:
        max-active: 10

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123.com
    username: root
    url: jdbc:mysql://localhost:3306/guli?characterEncoding=utf-8&serverTimezone=UTC&rewriteBatchedStatements=true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:com/lzg/guli/order/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #设置日志
