server:
  port: 8160

spring:
  application:
    name: service-ucenter
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123.com
    username: root
    url: jdbc:mysql://localhost:3306/guli?characterEncoding=utf-8&serverTimezone=UTC&rewriteBatchedStatements=true
      #设置返回时间的格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

    #配置redis
  redis:
    host: 192.168.0.11
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1 #最大堵塞等待时间，负数表示没有限制
        max-idle: 5
        min-idle: 0

  #设置mp xml文件的位置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:com/lzg/guli2/ucenter/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #设置日志


wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://localhost:8160/api/ucenter/wx/callback
